FROM php:8.2-apache

# ENV XZ_OPT="--no-sandbox"
# ENV XZ_DEFAULTS="--no-sandbox"

RUN docker-php-ext-install mysqli

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY composer.json ./
RUN composer install --no-dev --optimize-autoloader || true

COPY . .

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80